 CREATE TABLE TICKETBOOKING 
   (	PNRNO NUMBER, 
	TRAVELDATE DATE NOT NULL,
	SOURCE VARCHAR2(50)NOT NULL,
	DESTINATION VARCHAR2(50) NOT NULL,
	STATUS VARCHAR2(8) NOT NULL,
	SEATPREFERENCE VARCHAR2(7) NOT NULL,
	MEALPREFERENCE VARCHAR2(9) NOT NULL
);

SELECT PNRNO FROM TICKETBOOKING
INNER JOIN PASSENGERREGISTRATION ON
TICKETBOOKING.PNRNO=PASSENGERREGISTRATION.PASSENGERID;

INSERT INTO TICKETBOOKING (PNRNO,TRAVELDATE,SOURCE,DESTINATION,STATUS,SEATPREFERENCE,MEALPREFERENCE) VALUES ('1478523','05/05/2020','India','USA','Confirm','Window','Veg');
INSERT INTO TICKETBOOKING (PNRNO,TRAVELDATE,SOURCE,DESTINATION,STATUS,SEATPREFERENCE,MEALPREFERENCE) VALUES ('1478524','06/05/2020','India','Canada','New','Window','Veg');
INSERT INTO TICKETBOOKING (PNRNO,TRAVELDATE,SOURCE,DESTINATION,STATUS,SEATPREFERENCE,MEALPREFERENCE) VALUES ('1478525','06/06/2020','India','China','Hold','Aside','Non-veg');
INSERT INTO TICKETBOOKING (PNRNO,TRAVELDATE,SOURCE,DESTINATION,STATUS,SEATPREFERENCE,MEALPREFERENCE) VALUES ('1478526','08/08/2020','India','California','Hold','Middle','Non-veg');
INSERT INTO TICKETBOOKING (PNRNO,TRAVELDATE,SOURCE,DESTINATION,STATUS,SEATPREFERENCE,MEALPREFERENCE) VALUES ('1478527','01/07/2021','India','Shrilanka','New','Middle','Veg');
INSERT INTO TICKETBOOKING (PNRNO,TRAVELDATE,SOURCE,DESTINATION,STATUS,SEATPREFERENCE,MEALPREFERENCE) VALUES ('1478528','02/07/2021','India','Canada','Confirm','Aside','Veg'); 
INSERT INTO TICKETBOOKING (PNRNO,TRAVELDATE,SOURCE,DESTINATION,STATUS,SEATPREFERENCE,MEALPREFERENCE) VALUES ('1478529','03/07/2021','India','USA','New','Window','Non-veg');
INSERT INTO TICKETBOOKING (PNRNO,TRAVELDATE,SOURCE,DESTINATION,STATUS,SEATPREFERENCE,MEALPREFERENCE) VALUES ('1478530','04/07/2021','India','California','Hold','Aside','Veg');
INSERT INTO TICKETBOOKING (PNRNO,TRAVELDATE,SOURCE,DESTINATION,STATUS,SEATPREFERENCE,MEALPREFERENCE) VALUES ('1478531','05/07/2021','India','Shrilanka','Confirm','Middle','Veg');
INSERT INTO TICKETBOOKING (PNRNO,TRAVELDATE,SOURCE,DESTINATION,STATUS,SEATPREFERENCE,MEALPREFERENCE) VALUES ('1478532','06/07/2021','India','Japan','New','Window','Non-veg');
