  CREATE TABLE MASTERDATA 
   (	
	PASSENGERID NUMBER(7),	
	BOOKINGSTATUS VARCHAR2(10)NOT NULL,
	SEATPREFERENCE VARCHAR2(10) NOT NULL,
	MEALPREFERENCE VARCHAR2(10) NOT NULL
   );

INSERT INTO MASTERDATA (PASSENGERID,BOOKINGSTATUS,SEATPREFERENCE,MEALPREFERENCE) VALUES ('1000001','Confirm','Window','Veg');
INSERT INTO MASTERDATA (PASSENGERID,BOOKINGSTATUS,SEATPREFERENCE,MEALPREFERENCE) VALUES ('1000002','New','Window','Veg');
INSERT INTO MASTERDATA (PASSENGERID,BOOKINGSTATUS,SEATPREFERENCE,MEALPREFERENCE) VALUES ('1000001','Hold','Aside','Non-veg');
INSERT INTO MASTERDATA (PASSENGERID,BOOKINGSTATUS,SEATPREFERENCE,MEALPREFERENCE) VALUES ('1000001','Hold','Middle','Non-veg');
